### ISSUE TITLE
Swetrix.js v2 release

### ISSUE THREAD

**Issue by Blaumaus** [ansidev/swetrix-vue#35]
Hi! Could you please release a new version of `swetrix-vue` module which includes `swetrix` v2.0.0 in it?
It's needed so the customers that use `swetrix-vue` would be able to see `Performance` data in their Dashboards.

Thank you and thanks for creating this amazing plugin.

**Comment by ansidev** [comment]
@Blaumaus I've read the v2 changelog. It has a breaking change. Therefore, I'm wondering if there is a migration guide or just need to upgrade the version. At this moment, I don't have enough time to evaluate this point. That's why I'm not released a new version.

Btw, this is an open-source, so everyone can submit PRs. I'm happy to review all of them and merge if they are OK.

**Comment by Blaumaus** [comment]
@ansidev it will be fine if you just upgrade to v2. The breaking change is that `trackViews` is now asynchronous, but swetrix-vue just calls the function without using it's return value so it won't break anything if you upgrade.

**Comment by ansidev** [comment]
@Blaumaus Released [v2](https://github.com/ansidev/swetrix-vue/releases/tag/v2.0.0).
